---
title: "Case Study 1 - Morphine"
author: "Emily Gentles, Weiyi Liu, Jack McCarthy, Qinzhe Wang"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: beamer_presentation
    theme: cyborg
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(gridExtra)
library(cowplot)
library(knitr)
require(magrittr)
require(dplyr)
library(kableExtra)
library(readr)
library(tidyr)
library(broom)
library(lme4)
library(glmmTMB)
library(sjPlot)
library(brms)
library(coda)
library(rstan)
library(tidybayes)
library(naniar)
library(olsrr)
```

```{r echo = FALSE}
load('streetrx.RData')
```

```{r echo = FALSE, message = FALSE, warning = FALSE}
# subset for group drug
streetrx[streetrx == ""] <- NA
morph_data <- streetrx %>%
  drop_na() %>%
  clean_names() %>%
  filter(api_temp == 'morphine') %>%
  mutate(
    quarter=substring(yq_pdate, 5, 5),
    year=substring(yq_pdate, 1, 4)
  )
```


```{r echo = FALSE, message = FALSE, warning = FALSE}
# replace state "USA" with "Unknown"
morph_data$state <- recode_factor(droplevels(morph_data$state), "USA" = "Unknown")

```


# EDA 

```{r, fig.width=8, fig.height=3.5, echo = FALSE, message = FALSE, warning = FALSE}
morph_trunc <- morph_data %>%
  filter(between(ppm, quantile(ppm, 0.001), quantile(ppm, 0.999)))

p1 <- morph_trunc %>%
  ggplot(aes(x=ppm)) +
    geom_histogram(
      aes(y=..density..), 
      color='black', 
      linetype='dashed',
      size=0.5,
      fill='lightblue', 
      alpha=0.5,
      bins=20
    ) +
    geom_density(size=0.75, bw=0.3) +
    labs(title='Distribution of morphine ppm') +
    theme_bw()

p2 <- morph_trunc %>%
  ggplot(aes(x=log(ppm))) +
    geom_histogram(
      aes(y=..density..), 
      color='black', 
      linetype='dashed',
      size=0.5,
      fill='lightcoral', 
      alpha=0.5,
      bins=20
    ) +
    geom_density(size=0.75, bw=0.3) +
    labs(title='Distribution of morphine log(ppm)') +
    xlim(-7, 3) +
    theme_bw()

jpeg("EDAplot1.jpg", width = 600)

grid.arrange(p1, p2, ncol=2)

dev.off()
```


```{r echo = FALSE, warning = FALSE, fig.width=5}
state_size <- morph_data %>%
  group_by(state) %>%
  summarise(n = n(), .groups = "drop")  %>%
  arrange(n) %>%
  pivot_wider(names_from = state,
            values_from = n)

small_sample <- state_size %>% 
  dplyr::select(1:5) %>% 
  kable(caption = "7 states with smallest sample size ",
        align = "c")

small_sample

morph_data$state <- as.character(morph_data$state)

# remove states that have small sample size
morph_data <- morph_data %>%
  filter(state != "North Dakota") %>%
  filter(state != "Washington, DC") %>%
  filter( state != "Vermont") %>%
  filter(state != "Wyoming") %>%
  filter(state != "Alaska")
```

# EDA 

```{r, fig.width=10, fig.height=3, echo = FALSE}
morph_state <- morph_trunc %>%
  filter(state %in% state.name) %>%
  mutate(state_abv=state.abb[match(state,state.name)])

morph_state <- morph_state %>%
  filter(state != "North Dakota") %>%
  filter(state != "Washington, DC") %>%
  filter( state != "Vermont") %>%
  filter(state != "Wyoming") %>%
  filter(state != "Alaska")

grand_mean <- mean(morph_state$ppm)

p3 <- morph_state %>%
  group_by(state_abv) %>%
  summarise(n = n(), mean = mean(ppm)) %>%
  ggplot(aes(x=n, y=mean)) +
    geom_hline(
      aes(yintercept=grand_mean),
      linetype='dashed',
      color='red',
      size=0.75
    ) +
    geom_point() +
    labs(x='sample size', y='mean log(ppm)') +
    theme_bw() +
  labs(x = "Sample Size", y = "Mean log(ppm)")

p4 <- morph_state %>%
  ggplot(aes(y=log(ppm), x=state_abv)) +
    geom_boxplot(
      fill=rainbow(45),
      alpha=0.5    
    ) +
    scale_x_discrete(guide=guide_axis(angle = 90)) +
    theme_bw() +
    labs(x='state') +
  labs(x = "State", y = "log(ppm)")

jpeg("EDAplot2.jpg", width = 700, height = 400)

cowplot::plot_grid(p3, p4, rel_widths = c(1, 2))

dev.off()
```

# Model Selection

# Model

# Model Diagnosics

# Findings
